require: 
  - ts-node/register
include: 
  - src/**/*.ts
exclude:
  - tests/**/*
reporter: 
  - lcov
  - text
extension:
  - .ts
all: true
temp-dir: .nyc/temp
report-dir: .nyc/coverage-reports
check-coverage: false
branches: 70
lines: 90
functions: 70
statements: 90